pushing pacts

diff --git a/.github/workflows/release_pipeline.yml b/.github/workflows/release_pipeline.yml
--- a/.github/workflows/release_pipeline.yml
+++ b/.github/workflows/release_pipeline.yml
@@ -65,4 +65,45 @@ jobs:
           tag_name: ${{ env.VERSION }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
+      - name: Checkout wms-contracts repo
+        uses: actions/checkout@v3
+        with:
+          repository: kityk-cargo/wms-contracts
+          path: ./wms-contracts
+        
+      - name: Checkout transient pact files
+        uses: actions/checkout@v3
+        with:
+          ref: pacts-transient-do_not_touch
+          path: ./pacts-transient
+
+      - name: Verify push token exists
+        shell: bash
+        env:
+          CONTRACTS_PUSH_TOKEN: ${{ secrets.CONTRACTS_PUSH_TOKEN }}
+        run: |
+          if [ -z "$CONTRACTS_PUSH_TOKEN" ]; then
+            echo "Error: CONTRACTS_PUSH_TOKEN not defined" >&2
+            exit 1
+          fi
+          echo "Verified: CONTRACTS_PUSH_TOKEN exists"
+
+      - name: Publish Pact files to contracts repo
+        env:
+          CONTRACTS_PUSH_TOKEN: ${{ secrets.CONTRACTS_PUSH_TOKEN }}  # must be set with write permissions
+        run: |
+            mkdir -p ./wms-contracts/pact/ui
+            cp -r ./pacts-transient/pacts/* ./wms-contracts/pact/ui/
+            cd ./wms-contracts
+            git add -f .
+            if ! git diff-index --quiet HEAD --; then
+              git config --global user.email "contract@updater.com"
+              git config --global user.name "Fast Tests Angel"
+              git commit -m "Update UI pact files"
+              git config --unset-all http.https://github.com/.extraheader
+              git push -f https://$CONTRACTS_PUSH_TOKEN@github.com/kityk-cargo/wms-contracts.git main
+            else
+              echo "No changes to publish"
+            fi
         
